[platformio]
boards_dir = boards
default_envs = T5-ePaper-S3

[env]
platform = espressif32@6.5.0
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=3

monitor_filters = 
	default
	esp32_exception_decoder

lib_deps = 
    file:///home/whisker/Development/lillygo4.7_display/src/lilygo_epd47_s3
	lewisxhe/SensorLib @ 0.3.1
	Wire
	SPI
    SD

[env:T5-ePaper-S3]
extends = env
board = T5-ePaper-S3
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47_S3
board_build.filesystem = spiffs
